import { PlaceCategory, PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const places = [
  {
    slug: 'obelisco-de-buenos-aires',
    nameEs: 'Obelisco de Buenos Aires',
    nameEn: 'Buenos Aires Obelisk',
    category: PlaceCategory.MONUMENT,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6037342',
    longitude: '-58.3815704',
    summarySeedEs: 'Monumento emblematico inaugurado en 1936 sobre la Avenida 9 de Julio, uno de los puntos urbanos mas reconocibles de Buenos Aires.',
    summarySeedEn: 'Iconic monument inaugurated in 1936 on Avenida 9 de Julio, one of the most recognizable urban landmarks in Buenos Aires.',
    scientificRelevance: 'Urban planning, city development and modern public monument design.',
    editorialScore: 98,
    isFeatured: true,
  },
  {
    slug: 'planetario-galileo-galilei',
    nameEs: 'Planetario Galileo Galilei',
    nameEn: 'Galileo Galilei Planetarium',
    category: PlaceCategory.SCIENTIFIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.5690419',
    longitude: '-58.4116578',
    summarySeedEs: 'Planetario ubicado en Palermo, dedicado a la divulgacion astronomica y a experiencias inmersivas sobre el cosmos.',
    summarySeedEn: 'Planetarium in Palermo focused on astronomy outreach and immersive experiences about the cosmos.',
    scientificRelevance: 'Astronomy education, scientific outreach and public science engagement.',
    editorialScore: 100,
    isFeatured: true,
  },
  {
    slug: 'museo-argentino-de-ciencias-naturales',
    nameEs: 'Museo Argentino de Ciencias Naturales',
    nameEn: 'Argentine Museum of Natural Sciences',
    category: PlaceCategory.SCIENTIFIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6054275',
    longitude: '-58.4356854',
    summarySeedEs: 'Museo cientifico historico con colecciones de paleontologia, zoologia, geologia y biodiversidad argentina.',
    summarySeedEn: 'Historic science museum with collections in paleontology, zoology, geology and Argentine biodiversity.',
    scientificRelevance: 'Natural history, paleontology, biodiversity and science education.',
    editorialScore: 99,
    isFeatured: true,
  },
  {
    slug: 'cabildo-de-buenos-aires',
    nameEs: 'Cabildo de Buenos Aires',
    nameEn: 'Buenos Aires Cabildo',
    category: PlaceCategory.HISTORIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6080558',
    longitude: '-58.3731916',
    summarySeedEs: 'Edificio historico colonial asociado a la Revolucion de Mayo y a la administracion temprana de la ciudad.',
    summarySeedEn: 'Historic colonial building associated with the May Revolution and the city’s early administration.',
    scientificRelevance: 'Historical interpretation, colonial urban development and civic history.',
    editorialScore: 96,
    isFeatured: true,
  },
  {
    slug: 'plaza-de-mayo',
    nameEs: 'Plaza de Mayo',
    nameEn: 'Plaza de Mayo',
    category: PlaceCategory.PLAZA,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6089473',
    longitude: '-58.3707991',
    summarySeedEs: 'Plaza central del casco historico, escenario de eventos politicos y sociales clave en la historia argentina.',
    summarySeedEn: 'Central square in the historic district, site of key political and social events in Argentine history.',
    scientificRelevance: 'Urban history, civic space and collective memory in public environments.',
    editorialScore: 97,
    isFeatured: true,
  },
  {
    slug: 'floralis-generica',
    nameEs: 'Floralis Generica',
    nameEn: 'Floralis Generica',
    category: PlaceCategory.MONUMENT,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.5822701',
    longitude: '-58.3923558',
    summarySeedEs: 'Escultura metalica monumental con sistema de apertura de petalos, ubicada en Plaza Naciones Unidas.',
    summarySeedEn: 'Large metallic sculpture with petal-opening mechanics located in Plaza Naciones Unidas.',
    scientificRelevance: 'Engineering, kinetic sculpture and material design in public art.',
    editorialScore: 93,
    isFeatured: true,
  },
  {
    slug: 'puente-de-la-mujer',
    nameEs: 'Puente de la Mujer',
    nameEn: 'Puente de la Mujer',
    category: PlaceCategory.MONUMENT,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6116165',
    longitude: '-58.3634634',
    summarySeedEs: 'Puente peatonal giratorio en Puerto Madero, reconocido por su ingenieria estructural y diseno contemporaneo.',
    summarySeedEn: 'Rotating pedestrian bridge in Puerto Madero, known for its structural engineering and contemporary design.',
    scientificRelevance: 'Structural engineering, movable bridge mechanics and contemporary urban design.',
    editorialScore: 95,
    isFeatured: true,
  },
  {
    slug: 'manzana-de-las-luces',
    nameEs: 'Manzana de las Luces',
    nameEn: 'Block of Enlightenment',
    category: PlaceCategory.HISTORIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6089814',
    longitude: '-58.3743501',
    summarySeedEs: 'Conjunto historico vinculado a instituciones educativas, religiosas y culturales de la ciudad.',
    summarySeedEn: 'Historic complex linked to educational, religious and cultural institutions in the city.',
    scientificRelevance: 'History of education, knowledge circulation and institutional development.',
    editorialScore: 91,
    isFeatured: true,
  },
  {
    slug: 'torre-monumental',
    nameEs: 'Torre Monumental',
    nameEn: 'Monumental Tower',
    category: PlaceCategory.MONUMENT,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.5924014',
    longitude: '-58.3741692',
    summarySeedEs: 'Torre reloj inaugurada a comienzos del siglo XX, pieza destacada del paisaje ferroviario y urbano de Retiro.',
    summarySeedEn: 'Clock tower inaugurated in the early 20th century, a key landmark in Retiro’s railway and urban landscape.',
    scientificRelevance: 'Timekeeping, urban infrastructure and architectural engineering.',
    editorialScore: 88,
    isFeatured: false,
  },
  {
    slug: 'parque-centenario',
    nameEs: 'Parque Centenario',
    nameEn: 'Centenario Park',
    category: PlaceCategory.PLAZA,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6054417',
    longitude: '-58.4352133',
    summarySeedEs: 'Parque urbano de referencia en Caballito, cercano a instituciones cientificas y culturales.',
    summarySeedEn: 'Major urban park in Caballito, close to scientific and cultural institutions.',
    scientificRelevance: 'Public urban ecology and civic use of scientific-cultural districts.',
    editorialScore: 84,
    isFeatured: false,
  },
  {
    slug: 'reserva-ecologica-costanera-sur',
    nameEs: 'Reserva Ecologica Costanera Sur',
    nameEn: 'Costanera Sur Ecological Reserve',
    category: PlaceCategory.SCIENTIFIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6216098',
    longitude: '-58.3578728',
    summarySeedEs: 'Area natural urbana de gran valor para observacion de aves, biodiversidad y educacion ambiental.',
    summarySeedEn: 'Urban nature reserve valuable for birdwatching, biodiversity and environmental education.',
    scientificRelevance: 'Urban ecology, wetlands, biodiversity and environmental observation.',
    editorialScore: 97,
    isFeatured: true,
  },
  {
    slug: 'congreso-de-la-nacion-argentina',
    nameEs: 'Congreso de la Nacion Argentina',
    nameEn: 'Argentine National Congress',
    category: PlaceCategory.HISTORIC_SITE,
    city: 'Ciudad Autonoma de Buenos Aires',
    country: 'Argentina',
    latitude: '-34.6090557',
    longitude: '-58.3926663',
    summarySeedEs: 'Palacio legislativo monumental, relevante por su arquitectura, materiales y simbolismo institucional.',
    summarySeedEn: 'Monumental legislative palace notable for its architecture, materials and institutional symbolism.',
    scientificRelevance: 'Monumental architecture, engineering and public institutional design.',
    editorialScore: 90,
    isFeatured: true,
  },
]

async function main() {
  for (const place of places) {
    await prisma.place.upsert({
      where: { slug: place.slug },
      update: place,
      create: place,
    })
  }

  console.log(`Seeded ${places.length} places.`)
}

main()
  .catch(async (error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
